#MX-64AR resolution : 4096 [pulse/rev]
# Angle : 360
# so it varies from o to 4095. 

#DX-117 resolution : 0.29[deg] = 1024 [pulse/rev]
# Angle : 300
# so it varies from 0 to 1023

# init <= This parameter is realted to the joint initial position, hence init. 
#         Since a full rotation is 360 degrees, 
#         setting init: 1023 (for MX-64AR) / 310 (for DX-117) would leave the initial state of the motor 90 degrees from the orifinal reference 0
#         setting init: 1365 (for MX-64AR) / 413 (for DX-117) would leave the initial state of the motor 120 degrees from the orifinal reference 0
#         setting init: 2047 (for MX-64AR) / 620 (for DX-117) would leave the initial state of the motor 180 degrees from the orifinal reference 0
#min, max <= minimun/maximum rotation the motor can do, it also follows the same rule as the previous parameters.

joint1_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: twintool_joint1
    joint_speed: 2.0
    motor:
        id: 1
        init: 2047
        min: 0
        max: 4095
